"""Scan presets for one-click mission profiles."""

SCAN_PRESETS = {
    "quick_recon": {
        "name": "Quick Recon",
        "icon": "bolt",
        "description": "Fast port scan + basic vuln check (5 min)",
        "directive": "Quick reconnaissance scan. Run nmap for port discovery and nuclei with top templates only. Do not enumerate directories or attempt exploitation.",
        "stealth_mode": False,
        "estimated_minutes": 5,
        "default_tools": ["nmap", "nuclei"],
        "phases": ["reconnaissance"],
        "scope_restrictions": {"max_depth": 1, "follow_redirects": False},
    },
    "full_assessment": {
        "name": "Full Assessment",
        "icon": "shield",
        "description": "Complete PTES pentest - all phases (30+ min)",
        "directive": "Perform a comprehensive penetration test following PTES methodology. Discover all services, enumerate thoroughly, scan for vulnerabilities, attempt exploitation of confirmed vulns, and generate a detailed report.",
        "stealth_mode": False,
        "estimated_minutes": 30,
        "default_tools": ["nmap", "nuclei", "nikto", "feroxbuster", "sqlmap", "metasploit"],
        "phases": ["reconnaissance", "enumeration", "vulnerability_scan", "exploitation", "reporting"],
        "scope_restrictions": {"max_depth": 5, "follow_redirects": True},
    },
    "web_only": {
        "name": "Web Application",
        "icon": "globe",
        "description": "Web-focused scan - OWASP Top 10 (15 min)",
        "directive": "Web application security assessment. Focus on web services only: directory enumeration, vulnerability scanning with nuclei web templates, SQL injection testing, and web server misconfiguration checks. Skip network-level attacks.",
        "stealth_mode": False,
        "estimated_minutes": 15,
        "default_tools": ["nuclei", "nikto", "feroxbuster", "sqlmap", "whatweb", "wpscan"],
        "phases": ["reconnaissance", "enumeration", "vulnerability_scan"],
        "scope_restrictions": {"ports": [80, 443, 8080, 8443], "protocols": ["http", "https"]},
    },
    "stealth": {
        "name": "Stealth Scan",
        "icon": "ghost",
        "description": "Low and slow - minimize detection (45+ min)",
        "directive": "Stealthy security assessment. Use slow timing, passive techniques first, minimize network noise. Avoid brute-force and aggressive scanning. Focus on passive recon and careful targeted probing.",
        "stealth_mode": True,
        "estimated_minutes": 45,
        "default_tools": ["nmap", "subfinder", "whatweb"],
        "phases": ["reconnaissance", "enumeration"],
        "scope_restrictions": {"rate_limit": "slow", "no_brute_force": True},
    },
    "exploit_focus": {
        "name": "Exploitation Focus",
        "icon": "crosshairs",
        "description": "Skip recon, focus on exploiting known vulns",
        "directive": "Exploitation-focused assessment. Perform minimal discovery then immediately attempt exploitation of any discovered services. Prioritize CVE-based exploits and default credential checks. Generate custom exploits if needed.",
        "stealth_mode": False,
        "estimated_minutes": 20,
        "default_tools": ["nmap", "metasploit", "searchsploit", "hydra"],
        "phases": ["reconnaissance", "exploitation"],
        "scope_restrictions": {"max_depth": 3, "follow_redirects": True},
    },
    "api_security": {
        "name": "API Security",
        "icon": "code",
        "description": "REST/GraphQL API assessment (15 min)",
        "directive": "API security assessment. Discover API endpoints, test for authentication bypass, injection flaws, IDOR vulnerabilities, and misconfigured CORS. Focus on the API attack surface.",
        "stealth_mode": False,
        "estimated_minutes": 15,
        "default_tools": ["nuclei", "ffuf", "sqlmap", "httpx"],
        "phases": ["reconnaissance", "enumeration", "vulnerability_scan"],
        "scope_restrictions": {"protocols": ["http", "https"], "focus": "api_endpoints"},
    },
    "ad_assessment": {
        "name": "Active Directory Assessment",
        "icon": "sitemap",
        "description": "AD enumeration and exploitation (30+ min)",
        "directive": "Active Directory security assessment. Enumerate domain controllers, users, groups, GPOs, and trust relationships. Test for Kerberoasting, AS-REP roasting, credential relay attacks, and privilege escalation paths. Identify misconfigurations in AD CS, delegation, and ACLs.",
        "stealth_mode": False,
        "estimated_minutes": 30,
        "default_tools": ["nmap", "enum4linux", "kerbrute", "crackmapexec", "impacket"],
        "phases": ["reconnaissance", "enumeration", "vulnerability_scan", "exploitation"],
        "scope_restrictions": {
            "ports": [88, 135, 139, 389, 445, 636, 3268, 3269],
            "protocols": ["ldap", "smb", "kerberos"],
        },
    },
    "cloud_security": {
        "name": "Cloud Security Assessment",
        "icon": "cloud",
        "description": "Cloud misconfiguration and exposure check (20 min)",
        "directive": "Cloud security assessment. Identify exposed cloud services, misconfigured storage buckets, overly permissive IAM policies, and publicly accessible resources. Check for metadata service exposure, insecure API gateways, and cloud-specific vulnerabilities across AWS, Azure, and GCP.",
        "stealth_mode": False,
        "estimated_minutes": 20,
        "default_tools": ["nuclei", "httpx", "nmap", "ffuf"],
        "phases": ["reconnaissance", "enumeration", "vulnerability_scan"],
        "scope_restrictions": {"protocols": ["http", "https"], "focus": "cloud_services"},
    },
}
