"""
Tool Execution Service.

Centralizes the execution of security tools with mandatory safety checks,
consensus validation, and output management.
"""

from __future__ import annotations

import asyncio
import logging
import re
import uuid
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

from app.services.ai.agents.base import AgentContext, ToolAction
from app.services.ai.agents.safety import SafetySupervisorAgent
from app.services.ai.consensus import VotingSystem
from app.services.tools.adapter import CommandToolAdapter
from app.services.tools.models import ToolExecutionRequest, ToolExecutionResult
from app.services.tools.registry import get_registry
from app.services.tools.result_processor import (
    log_success,
    record_to_memory,
    update_attack_surface_from_finding,
)
from app.services.tools.safety import (
    perform_consensus_check,
    perform_safety_check,
    perform_safety_check_with_retry,
)

if TYPE_CHECKING:
    from app.services.mission.mission import Mission

logger = logging.getLogger("spectra.tools.service")

try:
    import jsonschema

    HAS_JSONSCHEMA = True
except ImportError:
    HAS_JSONSCHEMA = False
    logger.warning("jsonschema not installed — tool argument validation disabled")

import html

from app.services.ai.context import truncate_for_llm


def sanitize_tool_output(output: str) -> str:
    """Sanitize tool output for safe display in the UI."""
    return html.escape(output)


class StandaloneMissionAdapter:
    """Adapts a standalone execution to the Mission interface."""

    def __init__(self, target: str, job_id: str | None = None):
        import uuid

        self.id = job_id or str(uuid.uuid4())
        self.target = target
        self.directive = f"Execute tool against {target}"
        self.findings: list[dict[str, Any]] = []
        self.tool_runs: list[str] = []

    def log(self, message: str) -> None:
        logger.info("[%s] %s", self.id, message)

    def add_finding(self, finding: dict[str, Any]) -> None:
        self.findings.append(finding)

    def record_tool_run(self, tool_name: str) -> None:
        self.tool_runs.append(tool_name)


class ToolExecutionService:
    """
    Service responsible for executing security tools safely.

    Responsibilities:
    1. Validate tool availability and configuration
    2. Enforce SafetySupervisor checks on ALL commands
    3. Enforce VotingSystem (Consensus) for high-risk actions
    4. Manage consistent output directories
    5. Execute tools via PostgreSQL job queue worker in the tools container
    """

    # --- Tuneable constants ---------------------------------------------------
    DEFAULT_TIMEOUT = 300  # seconds
    JOB_BUFFER_TIMEOUT = 60  # extra seconds on top of tool timeout
    MAX_STDOUT_CHARS = 3000
    MAX_STDERR_CHARS = 500
    INSTALL_TIMEOUT = 600  # seconds
    MAX_CONCURRENCY = 5
    MAX_RETRIES = 2

    @staticmethod
    def _get_queue_name(mission_id: str) -> str:
        """Get the queue name for a mission's sandbox worker."""
        from app.services.tools.sandbox.models import SandboxInfo

        return SandboxInfo.make_queue_name(mission_id)

    def __init__(self, llm_client: Any):
        """Initialize with LLM client for safety/consensus agents."""
        self.llm = llm_client
        self.safety_supervisor = SafetySupervisorAgent(llm_client)
        self.consensus = VotingSystem(llm_client)

        # Concurrency limit
        self._semaphore = asyncio.Semaphore(self.MAX_CONCURRENCY)

    async def execute_tool_action(self, mission: Mission, action: ToolAction, context: AgentContext) -> bool:
        """
        Execute a tool action generated by an agent.

        Args:
            mission: The mission context.
            action: The tool action to execute.
            context: The agent context.

        Returns:
            True if execution was successful, False otherwise.
        """
        result = await self.execute_request(
            mission=mission,
            tool_name=action.tool_name,
            target=action.target,
            args=action.tool_args,
            timeout=action.estimated_duration,
            risk_level=action.risk_level,
        )
        return result.success

    async def execute_custom_script(
        self,
        mission: Mission,
        script_content: str,
        language: str,
        target: str,
        args: list[str] | None = None,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> ToolExecutionResult:
        """
        Execute a custom generated script via the worker.
        """
        mission.log(f"[EXEC] Running custom {language} script against {target}")

        # Safety check: validate script content before execution
        is_safe, reason = await self._perform_safety_check(
            mission, script_content, f"custom_{language}_script", target, {}
        )
        if not is_safe:
            mission.log(f"[BLOCK] Custom script blocked by safety check: {reason}")
            return self._create_error_result(
                f"custom_{language}_script",
                target,
                f"Blocked by Safety Supervisor: {reason}",
            )

        from app.core.queue import Job, PostgresJobQueue

        try:
            queue_name = self._get_queue_name(mission.id) if hasattr(mission, "id") and mission.id else "default"
            queue = PostgresJobQueue(queue_name)
            job_id = await queue.enqueue_job(
                "execute_script_job",
                content=script_content,
                language=language,
                target=target,
                args=args,
                timeout=timeout,
            )

            job = Job(job_id)
            result_data = await job.result(timeout=timeout + self.JOB_BUFFER_TIMEOUT)

            if not result_data:
                return self._create_error_result("custom_script", target, "Job returned no result")

            success = result_data.get("success", False)
            mission.log(f"[{'OK' if success else 'FAIL'}] Script execution finished")
            if not success:
                mission.log(f"Error: {result_data.get('stderr')}")

            return ToolExecutionResult(
                tool_id=f"custom_{language}_script",
                target=target,
                success=success,
                exit_code=result_data.get("exit_code", -1),
                stdout=result_data.get("stdout", ""),
                stderr=result_data.get("stderr", ""),
                duration_seconds=0.0,  # Worker doesn't return duration for script job yet
            )

        except Exception as e:
            logger.error("Failed to execute custom script: %s", e)
            return self._create_error_result("custom_script", target, str(e))

    async def execute_request(
        self,
        mission: Mission,
        tool_name: str,
        target: str,
        args: dict[str, Any] | None = None,
        timeout: int | None = None,
        risk_level: str = "low",
    ) -> ToolExecutionResult:
        """
        Execute a tool request with full safety and consensus checks.

        Returns:
            ToolExecutionResult object with stdout, stderr, etc.
        """
        try:
            # Normalize tool name to lowercase (LLMs sometimes use title-case)
            tool_name = self._normalize_tool_name(tool_name)

            # 1. Validation — reject invalid names before any lookups/installs
            if not self._validate_tool_name(tool_name):
                mission.log(f"Invalid tool name format: {tool_name}")
                return self._create_error_result(tool_name, target, "Invalid tool name")

            registry = get_registry()

            # Sync tool status from cache (set by worker in tools container)
            await registry.sync_status_from_cache()

            tool = registry.get_tool(tool_name)

            if not tool:
                mission.log(f"Tool {tool_name} not found in registry")
                return self._create_error_result(tool_name, target, "Tool not available")

            # Auto-install tool if not ready
            if not tool.is_available:
                mission.log(f"Tool {tool_name} not installed, installing...")
                install_success = await self._ensure_tool_installed(tool_name)
                if not install_success:
                    mission.log(f"Failed to install {tool_name}")
                    return self._create_error_result(tool_name, target, "Tool installation failed")
                mission.log(f"Tool {tool_name} installed successfully")
                # Refresh tool reference
                tool = registry.get_tool(tool_name)

            # Validate args against schema if available
            if tool.config.execution.args_schema:
                if HAS_JSONSCHEMA:
                    try:
                        jsonschema.validate(instance=args or {}, schema=tool.config.execution.args_schema)
                    except jsonschema.ValidationError as e:
                        return self._create_error_result(tool_name, target, f"Invalid arguments: {e}")
                else:
                    logger.warning("Skipping argument validation for %s — jsonschema not installed", tool_name)

            # 2. Preparation
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            run_id = f"{tool_name}_{timestamp}_{uuid.uuid4().hex[:4]}"
            output_dir = self._prepare_output_directory(mission.id, run_id)

            adapter = CommandToolAdapter(tool.config)

            request = ToolExecutionRequest(
                tool_id=tool_name,
                target=target,
                args=args or {},
                timeout=timeout,
            )

            # 3. Safety Check (Pre-flight) with retry on failure
            # Use the raw command (without docker exec wrapping) for safety
            # validation — this is the actual command the worker executes.
            full_command = adapter.builder.build_command(request, output_dir=str(output_dir))

            # Log detailed command info
            args_str = ", ".join(f"{k}={v}" for k, v in (args or {}).items()) if args else "default"
            mission.log(f"[EXEC] Executing: {tool_name} | Target: {target} | Args: {args_str}")
            mission.log(f"[CMD] Command: {full_command[:200]}{'...' if len(full_command) > 200 else ''}")

            # Safety check with auto-fix retry
            is_safe, reason, fixed_args = await self._perform_safety_check_with_retry(
                mission, full_command, tool_name, target, args, adapter, output_dir
            )
            if not is_safe:
                # Record the failed attempt for learning
                mission.record_tool_run(
                    tool_name,
                    args=args,
                    command=full_command,
                    success=False,
                    error=f"Safety blocked: {reason}",
                )
                return self._create_error_result(tool_name, target, f"Blocked by Safety Supervisor: {reason}")

            # Use fixed args if safety check corrected them
            if fixed_args is not None:
                request.args = fixed_args
                full_command = adapter.build_command(request, output_dir=str(output_dir))
                mission.log(f"[CMD] Fixed command: {full_command[:200]}{'...' if len(full_command) > 200 else ''}")

            # 4. Consensus Check (High Risk)
            if risk_level in ("high", "critical"):
                is_approved = await self._perform_consensus_check(mission, tool_name, risk_level)
                if not is_approved:
                    return self._create_error_result(tool_name, target, "Blocked by Consensus")

            # 5. Execution via job queue worker in tools container
            # Apply stealth delay if configured
            stealth = tool.config.stealth
            if stealth and isinstance(getattr(stealth, "delay_ms", None), (int, float)) and stealth.delay_ms:
                delay_s = stealth.delay_ms / 1000.0
                mission.log(f"[STEALTH] Applying {stealth.delay_ms}ms delay before execution")
                await asyncio.sleep(delay_s)

            # Apply stealth rate_limit args to command if configured
            if stealth and getattr(stealth, "extra_args", None):
                full_command = adapter.builder.apply_stealth_args(full_command, stealth)

            async with self._semaphore:
                result = await self._execute_via_worker(
                    tool_id=request.tool_id,
                    target=request.target,
                    args=request.args,
                    timeout=request.timeout,
                    output_dir=str(output_dir),
                    mission_id=mission.id,
                )

            if result.success:
                # Truncate raw output before it enters LLM-facing pipelines
                result.stdout = truncate_for_llm(result.stdout, max_chars=self.MAX_STDOUT_CHARS, label="stdout")
                result.stderr = truncate_for_llm(result.stderr, max_chars=self.MAX_STDERR_CHARS, label="stderr")
                self._log_success(mission, tool_name, result)
                for finding in result.parsed_findings:
                    mission.add_finding(finding)
                    self._update_attack_surface_from_finding(mission, finding)
                mission.record_tool_run(
                    tool_name,
                    args=args,
                    command=full_command,
                    success=True,
                )
            else:
                last_error = result.stderr[: self.MAX_STDERR_CHARS] if result.stderr else "No error message"
                mission.log(f"[ERROR] {tool_name} failed: {last_error[:200]}")
                mission.record_tool_run(
                    tool_name,
                    args=args,
                    success=False,
                    error=last_error,
                )

            # --- Learn from this execution ---
            self._record_to_memory(mission, tool_name, target, args, result)

            return result

        except Exception as e:
            msg = f"Critical error executing {tool_name}: {e}"
            mission.log(msg)
            logger.error(msg, exc_info=True)
            return self._create_error_result(tool_name, target, str(e))

    async def _execute_via_worker(
        self,
        tool_id: str,
        target: str,
        args: dict[str, Any] | None,
        timeout: int | None,
        output_dir: str,
        mission_id: str = "",
    ) -> ToolExecutionResult:
        """Execute tool via PostgreSQL job queue worker and wait for result."""
        from app.core.optimizations import tool_cache
        from app.core.queue import Job, PostgresJobQueue

        # Check cache first
        cached = tool_cache.get(tool_id, target, args or {})
        if cached is not None:
            logger.info("Using cached result for %s against %s", tool_id, target)
            return cached

        queue_name = self._get_queue_name(mission_id) if mission_id else "default"
        queue = PostgresJobQueue(queue_name)
        logger.debug("Routing job to queue '%s' (mission=%s)", queue_name, mission_id[:8] if mission_id else "none")

        try:
            # Enqueue the job
            job_id = await queue.enqueue_job(
                "execute_tool_job",
                tool_id=tool_id,
                target=target,
                args=args,
                timeout=timeout,
                output_dir=output_dir,
            )

            # Wait for result with timeout
            job_timeout = (timeout or self.DEFAULT_TIMEOUT) + self.JOB_BUFFER_TIMEOUT
            job = Job(job_id)
            result_data = await job.result(timeout=job_timeout)

            if result_data is None:
                return self._create_error_result(tool_id, target, "Job returned no result")

            # OOM escalation: recreate sandbox at next tier and retry
            if isinstance(result_data, dict) and result_data.get("oom") and mission_id:
                from app.services.tools.sandbox.escalation import attempt_oom_escalation

                escalated, message = await attempt_oom_escalation(mission_id)
                if escalated:
                    logger.warning("OOM escalation triggered for mission %s: %s", mission_id[:8], message)
                    return await self._execute_via_worker(
                        tool_id=tool_id,
                        target=target,
                        args=args,
                        timeout=timeout,
                        output_dir=output_dir,
                        mission_id=mission_id,
                    )
                else:
                    logger.error("OOM escalation failed for mission %s: %s", mission_id[:8], message)

            # Convert dict back to ToolExecutionResult and cache
            result = ToolExecutionResult(**result_data)
            # Sanitize output for safe UI display
            result.stdout = sanitize_tool_output(result.stdout)
            result.stderr = sanitize_tool_output(result.stderr)
            if result.success:
                tool_cache.set(tool_id, target, args or {}, result)
            return result

        except TimeoutError:
            return self._create_error_result(tool_id, target, f"Job timed out after {job_timeout}s")
        except Exception as e:
            logger.error("Worker execution failed: %s", e)
            return self._create_error_result(tool_id, target, f"Worker error: {e}")

    async def _ensure_tool_installed(self, tool_id: str) -> bool:
        """Ensure a tool is installed via the worker."""
        from app.core.queue import Job, PostgresJobQueue

        # Tool installs are global — always use the default queue
        queue = PostgresJobQueue()

        try:
            job_id = await queue.enqueue_job("install_tool_job", tool_id=tool_id)
            job = Job(job_id)

            # Wait for installation (can take a while for large tools)
            result = await job.result(timeout=self.INSTALL_TIMEOUT)

            if result and result.get("success"):
                # Update local registry status
                registry = get_registry()
                tool = registry.get_tool(tool_id)
                if tool:
                    from app.services.tools.models import ToolStatus

                    tool.status = ToolStatus.READY
                return True
            return False

        except Exception as e:
            logger.error("Tool installation failed: %s", e)
            return False

    def _create_error_result(self, tool_id: str, target: str, error: str) -> ToolExecutionResult:
        return ToolExecutionResult(
            tool_id=tool_id,
            target=target,
            success=False,
            stdout="",
            stderr=str(error),
            exit_code=-1,  # Internal error
            duration_seconds=0.0,
        )

    async def _perform_safety_check(
        self,
        mission: Mission,
        command: str,
        tool_name: str,
        target: str,
        args: dict[str, Any] | None,
    ) -> tuple[bool, str]:
        """Run the command through the Safety Supervisor."""
        return await perform_safety_check(self.safety_supervisor, mission, command, tool_name, target, args)

    async def _perform_safety_check_with_retry(
        self,
        mission: Mission,
        command: str,
        tool_name: str,
        target: str,
        args: dict[str, Any] | None,
        builder: CommandToolAdapter,
        output_dir: Path,
        max_retries: int = MAX_RETRIES,
    ) -> tuple[bool, str, dict[str, Any] | None]:
        """Run safety check with automatic command fixing on failure."""
        return await perform_safety_check_with_retry(
            self.safety_supervisor,
            self.llm,
            mission,
            command,
            tool_name,
            target,
            args,
            builder,
            output_dir,
            max_retries,
        )

    async def _perform_consensus_check(self, mission: Mission, tool_name: str, risk_level: str) -> bool:
        """Get consensus for high-risk actions."""
        return await perform_consensus_check(self.consensus, mission, tool_name, risk_level)

    def _record_to_memory(
        self,
        mission: Mission,
        tool_name: str,
        target: str,
        args: dict[str, Any] | None,
        result: ToolExecutionResult,
    ) -> None:
        """Record tool execution results to persistent memory for learning."""
        record_to_memory(mission, tool_name, target, args, result)

    def _prepare_output_directory(self, mission_id: str, run_id: str) -> Path:
        """Create and return the output directory path."""
        path = Path("data/missions") / mission_id / "scans" / run_id
        path.mkdir(parents=True, exist_ok=True)
        return path

    def _validate_tool_name(self, tool_name: str) -> bool:
        """Validate tool name for filesystem safety."""
        return bool(re.match(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$", tool_name))

    def _normalize_tool_name(self, tool_name: str) -> str:
        """
        Normalize tool names to match plugin IDs.

        LLMs often use title-case like "Metasploit Framework" but plugin IDs are lowercase.
        """
        tool_aliases = {
            "metasploit framework": "metasploit",
            "metasploit": "metasploit",
            "hydra": "hydra",
            "nuclei": "nuclei",
            "nmap": "nmap",
            "nikto": "nikto",
            "gobuster": "gobuster",
            "wpscan": "wpscan",
            "sqlmap": "sqlmap",
            "searchsploit": "searchsploit",
            "ffuf": "ffuf",
            "naabu": "naabu",
            "amass": "amass",
        }

        normalized = tool_name.lower().strip()
        return tool_aliases.get(normalized, normalized)

    def _log_success(self, mission: Mission, tool_name: str, result: ToolExecutionResult) -> None:
        """Log detailed successful execution summary."""
        log_success(mission, tool_name, result)

    def _update_attack_surface_from_finding(self, mission: Mission, finding: dict[str, Any]) -> None:
        """Update attack surface from a parsed finding."""
        update_attack_surface_from_finding(mission, finding)
