"""
Tool Execution Service.

Thin orchestrator that delegates to focused modules:
- validation.py  — tool name checks, registry resolution, auto-install
- safety_checks.py — SafetySupervisor gate + retry-with-fix
- consensus.py — VotingSystem gate for high-risk actions
- dispatch.py — request building, worker dispatch, result processing
"""

from __future__ import annotations

import asyncio
import html
import logging
from typing import TYPE_CHECKING, Any

from app.services.ai.agents.base import AgentContext, ToolAction
from app.services.ai.agents.safety import SafetySupervisorAgent
from app.services.ai.consensus import VotingSystem
from app.services.tools.consensus import perform_consensus_check
from app.services.tools.dispatch import build_execution_request, dispatch_and_process_result
from app.services.tools.models import ToolExecutionResult
from app.services.tools.output import (
    create_error_result,
    normalize_tool_name,
    record_to_memory,
)
from app.services.tools.safety_checks import (
    perform_safety_check,
    perform_safety_check_with_retry,
)
from app.services.tools.validation import validate_and_resolve_tool

# Keep these imports in *this* module's namespace so that existing tests
# (which ``patch("app.services.tools.service.<Name>")`` ) keep working.
from spectra_common.constants import (
    TOOL_DEFAULT_TIMEOUT,
    TOOL_INSTALL_TIMEOUT,
    TOOL_JOB_BUFFER_TIMEOUT,
    TOOL_MAX_CONCURRENCY,
    TOOL_MAX_RETRIES,
    TOOL_MAX_STDERR_CHARS,
    TOOL_MAX_STDOUT_CHARS,
)
from spectra_domain.jobs import WorkerJobName

if TYPE_CHECKING:
    from app.services.ai.llm import LLMClient
    from app.services.mission.mission import Mission

logger = logging.getLogger(__name__)


def sanitize_tool_output(output: str) -> str:
    """Sanitize tool output for safe display in the UI."""
    return html.escape(output)


class StandaloneMissionAdapter:
    """Adapts a standalone execution to the Mission interface."""

    def __init__(self, target: str, job_id: str | None = None, user_id: str | None = None):
        import uuid as _uuid

        self.id = job_id or str(_uuid.uuid4())
        self.target = target
        self.user_id = user_id or "__standalone__"
        self.directive = f"Execute tool against {target}"
        self.findings: list[dict[str, Any]] = []
        self.tool_runs: list[str] = []

    def log(self, message: str) -> None:
        logger.info("[%s] %s", self.id, message)

    def add_finding(self, finding: dict[str, Any]) -> None:
        self.findings.append(finding)

    def record_tool_run(self, tool_name: str) -> None:
        self.tool_runs.append(tool_name)


class ToolExecutionService:
    """
    Service responsible for executing security tools safely.

    Orchestrates validation, safety, consensus, and execution dispatch
    by delegating to focused helper modules.
    """

    # --- Tuneable constants (defined in spectra_common.constants) ------------------
    DEFAULT_TIMEOUT = TOOL_DEFAULT_TIMEOUT
    JOB_BUFFER_TIMEOUT = TOOL_JOB_BUFFER_TIMEOUT
    MAX_STDOUT_CHARS = TOOL_MAX_STDOUT_CHARS
    MAX_STDERR_CHARS = TOOL_MAX_STDERR_CHARS
    INSTALL_TIMEOUT = TOOL_INSTALL_TIMEOUT
    MAX_CONCURRENCY = TOOL_MAX_CONCURRENCY
    MAX_RETRIES = TOOL_MAX_RETRIES

    @staticmethod
    def _get_queue_name(mission_id: str) -> str:
        """Get the queue name for tool execution.

        Uses mission-specific queue if sandbox container exists,
        otherwise routes to shared tools worker queue.
        """
        from app.services.tools.sandbox import get_sandbox_pool
        from app.services.tools.sandbox.models import SandboxInfo

        pool = get_sandbox_pool()
        if pool and pool.available:
            return SandboxInfo.make_queue_name(mission_id)

        # Shared tools worker in containerized deployment
        from app.core.config import settings

        return settings.TOOL_QUEUE_NAME

    def __init__(self, llm_client: LLMClient):
        """Initialize with LLM client for safety/consensus agents."""
        self.llm = llm_client
        self.safety_supervisor = SafetySupervisorAgent(llm_client)
        self.consensus = VotingSystem(llm_client)

        # Concurrency limit
        self._semaphore = asyncio.Semaphore(self.MAX_CONCURRENCY)

    # --- Public entry points --------------------------------------------------

    async def execute_tool_action(self, mission: Mission, action: ToolAction, context: AgentContext) -> bool:
        """Execute a tool action generated by an agent."""
        result = await self.execute_request(
            mission=mission,
            tool_name=action.tool_name,
            target=action.target,
            args=action.tool_args,
            timeout=action.estimated_duration,
            risk_level=action.risk_level,
        )
        return result.success

    async def execute_custom_script(
        self,
        mission: Mission,
        script_content: str,
        language: str,
        target: str,
        args: list[str] | None = None,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> ToolExecutionResult:
        """Execute a custom generated script via the worker."""
        mission.log(f"[EXEC] Running custom {language} script against {target}")

        is_safe, reason = await self._perform_safety_check(
            mission, script_content, f"custom_{language}_script", target, {}
        )
        if not is_safe:
            mission.log(f"[BLOCK] Custom script blocked by safety check: {reason}")
            return create_error_result(
                f"custom_{language}_script",
                target,
                f"Blocked by Safety Supervisor: {reason}",
            )

        from app.infrastructure.queue import Job, PostgresJobQueue

        try:
            queue_name = self._get_queue_name(mission.id) if hasattr(mission, "id") and mission.id else "default"
            queue = PostgresJobQueue(queue_name)
            job_id = await queue.enqueue_job(
                WorkerJobName.EXECUTE_SCRIPT,
                content=script_content,
                language=language,
                target=target,
                args=args,
                timeout=timeout,
            )

            job = Job(job_id)
            result_data = await job.result(timeout=timeout + self.JOB_BUFFER_TIMEOUT)

            if not result_data:
                return create_error_result("custom_script", target, "Job returned no result")

            success = result_data.get("success", False)
            mission.log(f"[{'OK' if success else 'FAIL'}] Script execution finished")
            if not success:
                mission.log(f"Error: {result_data.get('stderr')}")

            return ToolExecutionResult(
                tool_id=f"custom_{language}_script",
                target=target,
                success=success,
                exit_code=result_data.get("exit_code", -1),
                stdout=result_data.get("stdout", ""),
                stderr=result_data.get("stderr", ""),
                duration_seconds=0.0,
            )

        except (OSError, TimeoutError, ValueError, RuntimeError) as e:
            logger.error("Failed to execute custom script: %s", e)
            return create_error_result("custom_script", target, str(e))

    async def execute_request(
        self,
        mission: Mission,
        tool_name: str,
        target: str,
        args: dict[str, Any] | None = None,
        timeout: int | None = None,
        risk_level: str = "low",
    ) -> ToolExecutionResult:
        """Execute a tool request with full safety and consensus checks."""
        try:
            tool_name = normalize_tool_name(tool_name)

            tool, error = await self._validate_and_resolve_tool(
                mission,
                tool_name,
                target,
                args,
            )
            if error is not None:
                return error
            if tool is None:
                return create_error_result(tool_name, target, f"Tool not found: {tool_name}")

            request, adapter, full_command, output_dir = build_execution_request(
                mission,
                tool,
                tool_name,
                target,
                args,
                timeout,
            )

            full_command, blocked = await self._apply_safety_and_consensus(
                mission,
                tool_name,
                target,
                args,
                risk_level,
                adapter,
                output_dir,
                request,
                full_command,
            )
            if blocked is not None:
                return blocked

            result = await self._dispatch_and_process_result(
                mission,
                tool,
                tool_name,
                target,
                args,
                request,
                adapter,
                full_command,
                output_dir,
            )

            record_to_memory(mission, tool_name, target, args, result)
            return result

        except (OSError, TimeoutError, ValueError, KeyError, RuntimeError) as e:
            msg = f"Critical error executing {tool_name}: {e}"
            mission.log(msg)
            logger.error(msg, exc_info=True)
            return create_error_result(tool_name, target, str(e))

    # --- Delegated helpers ----------------------------------------------------

    async def _validate_and_resolve_tool(self, mission, tool_name, target, args):
        return await validate_and_resolve_tool(
            mission,
            tool_name,
            target,
            args,
            self.INSTALL_TIMEOUT,
        )

    async def _apply_safety_and_consensus(
        self,
        mission,
        tool_name,
        target,
        args,
        risk_level,
        adapter,
        output_dir,
        request,
        full_command,
    ) -> tuple[str, ToolExecutionResult | None]:
        """Run safety check with retry and consensus check."""
        is_safe, reason, fixed_args = await self._perform_safety_check_with_retry(
            mission, full_command, tool_name, target, args, adapter, output_dir
        )
        if not is_safe:
            mission.record_tool_run(
                tool_name,
                args=args,
                command=full_command,
                success=False,
                error=f"Safety blocked: {reason}",
            )
            return full_command, create_error_result(tool_name, target, f"Blocked by Safety Supervisor: {reason}")

        if fixed_args is not None:
            request.args = fixed_args
            full_command = adapter.build_command(request, output_dir=output_dir)
            mission.log(f"[CMD] Fixed command: {full_command[:200]}{'...' if len(full_command) > 200 else ''}")

        if risk_level in ("high", "critical"):
            is_approved = await self._perform_consensus_check(mission, tool_name, risk_level)
            if not is_approved:
                return full_command, create_error_result(tool_name, target, "Blocked by Consensus")

        return full_command, None

    async def _dispatch_and_process_result(
        self,
        mission,
        tool,
        tool_name,
        target,
        args,
        request,
        adapter,
        full_command,
        output_dir,
    ) -> ToolExecutionResult:
        queue_name = self._get_queue_name(mission.id) if mission.id else "default"
        return await dispatch_and_process_result(
            mission,
            tool,
            tool_name,
            target,
            args,
            request,
            adapter,
            full_command,
            output_dir,
            semaphore=self._semaphore,
            queue_name=queue_name,
            default_timeout=self.DEFAULT_TIMEOUT,
            buffer_timeout=self.JOB_BUFFER_TIMEOUT,
            max_stdout_chars=self.MAX_STDOUT_CHARS,
            max_stderr_chars=self.MAX_STDERR_CHARS,
        )

    # --- Safety / Consensus (delegated) ----------------------------------------

    async def _perform_safety_check(
        self,
        mission,
        command,
        tool_name,
        target,
        args,
    ) -> tuple[bool, str]:
        return await perform_safety_check(
            mission,
            command,
            tool_name,
            target,
            args,
            self.safety_supervisor,
        )

    async def _perform_safety_check_with_retry(
        self,
        mission,
        command,
        tool_name,
        target,
        args,
        builder,
        output_dir,
        max_retries=MAX_RETRIES,
    ) -> tuple[bool, str, dict[str, Any] | None]:
        return await perform_safety_check_with_retry(
            mission,
            command,
            tool_name,
            target,
            args,
            builder,
            output_dir,
            self.safety_supervisor,
            self.llm,
            max_retries,
        )

    async def _perform_consensus_check(
        self,
        mission,
        tool_name,
        risk_level,
    ) -> bool:
        return await perform_consensus_check(
            mission,
            tool_name,
            risk_level,
            self.consensus,
        )
