"""
Tool Execution Service.

Centralizes the execution of security tools with mandatory safety checks,
consensus validation, and output management.
"""
from __future__ import annotations

import logging
import re
import uuid
import asyncio
from datetime import datetime
from pathlib import Path
from typing import Any, TYPE_CHECKING, cast

from app.core.config import settings
from app.services.tools.adapter.builder import CommandBuilder
from app.services.tools.models import ToolExecutionRequest, ToolExecutionResult
from app.services.tools.registry import get_registry
from app.services.ai.agents.base import AgentContext, ToolAction
from app.services.ai.agents.safety import SafetySupervisorAgent, SafetyInput, SafetyAction
from app.services.ai.llm import LLMClient
from app.services.ai.consensus import VotingSystem

if TYPE_CHECKING:
    from app.services.mission.mission import Mission

logger = logging.getLogger("spectra.tools.service")

class StandaloneMissionAdapter:
    """Adapts a standalone execution to the Mission interface."""

    def __init__(self, target: str, job_id: str | None = None):
        import uuid
        self.id = job_id or str(uuid.uuid4())
        self.target = target
        self.directive = f"Execute tool against {target}"
        self.findings: list[dict[str, Any]] = []
        self.tool_runs: list[str] = []

    def log(self, message: str) -> None:
        logger.info(f"[{self.id}] {message}")

    def add_finding(self, finding: dict[str, Any]) -> None:
        self.findings.append(finding)

    def record_tool_run(self, tool_name: str) -> None:
        self.tool_runs.append(tool_name)

class ToolExecutionService:
    """
    Service responsible for executing security tools safely.

    Responsibilities:
    1. Validate tool availability and configuration
    2. Enforce SafetySupervisor checks on ALL commands
    3. Enforce VotingSystem (Consensus) for high-risk actions
    4. Manage consistent output directories
    5. Execute tools via ARQ worker in the tools container
    """

    def __init__(self, llm_client: Any):
        """Initialize with LLM client for safety/consensus agents."""
        self.llm = llm_client
        self.safety_supervisor = SafetySupervisorAgent(llm_client)
        self.consensus = VotingSystem(llm_client)

        # Concurrency limit
        self._semaphore = asyncio.Semaphore(5)

    async def execute_tool_action(
        self, mission: "Mission", action: ToolAction, context: AgentContext
    ) -> bool:
        """
        Execute a tool action generated by an agent.

        Args:
            mission: The mission context.
            action: The tool action to execute.
            context: The agent context.

        Returns:
            True if execution was successful, False otherwise.
        """
        result = await self.execute_request(
            mission=mission,
            tool_name=action.tool_name,
            target=action.target,
            args=action.tool_args,
            timeout=action.estimated_duration,
            risk_level=action.risk_level,
        )
        return result.success

    async def execute_request(
        self,
        mission: "Mission",
        tool_name: str,
        target: str,
        args: dict[str, Any] | None = None,
        timeout: int | None = None,
        risk_level: str = "low",
    ) -> ToolExecutionResult:
        """
        Execute a tool request with full safety and consensus checks.

        Returns:
            ToolExecutionResult object with stdout, stderr, etc.
        """
        try:
            # Normalize tool name to lowercase (LLMs sometimes use title-case)
            tool_name = self._normalize_tool_name(tool_name)

            # 1. Validation
            registry = get_registry()

            # Sync tool status from Redis (set by worker in tools container)
            await registry.sync_status_from_redis()

            tool = registry.get_tool(tool_name)

            if not tool:
                mission.log(f"Tool {tool_name} not found in registry")
                return self._create_error_result(tool_name, target, "Tool not found")

            # Auto-install tool if not ready
            if not tool.is_available:
                mission.log(f"Tool {tool_name} not installed, installing...")
                install_success = await self._ensure_tool_installed(tool_name)
                if not install_success:
                    mission.log(f"Failed to install {tool_name}")
                    return self._create_error_result(
                        tool_name, target, "Tool installation failed"
                    )
                mission.log(f"Tool {tool_name} installed successfully")
                # Refresh tool reference
                tool = registry.get_tool(tool_name)

            if not self._validate_tool_name(tool_name):
                mission.log(f"Invalid tool name format: {tool_name}")
                return self._create_error_result(tool_name, target, "Invalid tool name")

            # Validate args against schema if available
            if tool.config.execution.args_schema:
                try:
                    import jsonschema

                    jsonschema.validate(
                        instance=args or {}, schema=tool.config.execution.args_schema
                    )
                except ImportError:
                    logger.warning("jsonschema not installed, skipping validation")
                except Exception as e:
                    return self._create_error_result(
                        tool_name, target, f"Invalid arguments: {e}"
                    )

            # 2. Preparation
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            run_id = f"{tool_name}_{timestamp}_{uuid.uuid4().hex[:4]}"
            output_dir = self._prepare_output_directory(mission.id, run_id)

            builder = CommandBuilder(tool.config)
            
            request = ToolExecutionRequest(
                tool_id=tool_name,
                target=target,
                args=args or {},
                timeout=timeout,
            )

            # 3. Safety Check (Pre-flight) with retry on failure
            full_command = builder.build_command(request, output_dir=str(output_dir))

            # Log detailed command info
            args_str = (
                ", ".join(f"{k}={v}" for k, v in (args or {}).items())
                if args
                else "default"
            )
            mission.log(
                f"[EXEC] Executing: {tool_name} | Target: {target} | Args: {args_str}"
            )
            mission.log(
                f"[CMD] Command: {full_command[:200]}{'...' if len(full_command) > 200 else ''}"
            )

            # Safety check with auto-fix retry
            is_safe, reason, fixed_args = await self._perform_safety_check_with_retry(
                mission, full_command, tool_name, target, args, builder, output_dir
            )
            if not is_safe:
                # Record the failed attempt for learning
                mission.record_tool_run(
                    tool_name,
                    args=args,
                    command=full_command,
                    success=False,
                    error=f"Safety blocked: {reason}",
                )
                return self._create_error_result(tool_name, target, f"Blocked by Safety Supervisor: {reason}")

            # Use fixed args if safety check corrected them
            if fixed_args is not None:
                request.args = fixed_args
                full_command = builder.build_command(
                    request, output_dir=str(output_dir)
                )
                mission.log(
                    f"[CMD] Fixed command: {full_command[:200]}{'...' if len(full_command) > 200 else ''}"
                )

            # 4. Consensus Check (High Risk)
            if risk_level in ("high", "critical"):
                is_approved = await self._perform_consensus_check(mission, tool_name, risk_level)
                if not is_approved:
                    return self._create_error_result(tool_name, target, "Blocked by Consensus")

            # 5. Execution (with Retry)
            return await self._execute_with_retry(
                mission, request, output_dir, max_retries=1
            )

        except Exception as e:
            msg = f"Critical error executing {tool_name}: {e}"
            mission.log(msg)
            logger.error(msg, exc_info=True)
            return self._create_error_result(tool_name, target, str(e))

    async def _execute_with_retry(
        self,
        mission: "Mission",
        request: ToolExecutionRequest,
        output_dir: Path,
        max_retries: int = 1,
    ) -> ToolExecutionResult:
        """Execute the tool via ARQ worker in the tools container."""
        
        last_result = None
        last_error = None

        async with self._semaphore:
            for attempt in range(max_retries + 1):
                if attempt > 0:
                    mission.log(f"[RETRY] Retrying {request.tool_id} (Attempt {attempt+1})...")
                    if request.timeout:
                        request.timeout *= 2

                try:
                    # Execute via ARQ worker in the tools container
                    result = await self._execute_via_worker(
                        tool_id=request.tool_id,
                        target=request.target,
                        args=request.args,
                        timeout=request.timeout,
                        output_dir=str(output_dir),
                    )
                    last_result = result

                    if result.success:
                        self._log_success(mission, request.tool_id, result)

                        for finding in result.parsed_findings:
                            mission.add_finding(finding)
                            # Update attack surface from findings
                            self._update_attack_surface_from_finding(mission, finding)

                        # Record successful execution with details
                        mission.record_tool_run(
                            request.tool_id,
                            args=request.args,
                            command=result.command
                            if hasattr(result, "command")
                            else None,
                            success=True,
                        )
                        return result
                    else:
                        last_error = (
                            result.stderr[:500] if result.stderr else "No error message"
                        )
                        mission.log(f"[ERROR] {request.tool_id} failed: {last_error[:200]}")

                        # Provide detailed error for LLM learning
                        if result.stderr:
                            mission.log(f"[INFO] Error details: {result.stderr[:500]}")
                        if result.stdout:
                            mission.log(f"[INFO] Output preview: {result.stdout[:300]}")

                        if result.stderr and (
                            "command not found" in result.stderr
                            or "permission denied" in result.stderr.lower()
                        ):
                            break
                            
                except Exception as e:
                    last_error = str(e)
                    mission.log(f"[ERROR] Execution error: {e}")
                    last_result = self._create_error_result(request.tool_id, request.target, str(e))
                
                if attempt < max_retries:
                    await asyncio.sleep(2)

        # Record failed execution for learning
        mission.record_tool_run(
            request.tool_id, args=request.args, success=False, error=last_error
        )

        return last_result or self._create_error_result(request.tool_id, request.target, "Unknown failure")

    async def _execute_via_worker(
        self,
        tool_id: str,
        target: str,
        args: dict[str, Any] | None,
        timeout: int | None,
        output_dir: str,
    ) -> ToolExecutionResult:
        """Execute tool via ARQ worker and wait for result."""
        from arq import create_pool
        from arq.connections import RedisSettings
        from app.core.config import settings

        redis_settings = RedisSettings(
            host=settings.REDIS_HOST,
            port=settings.REDIS_PORT,
            password=settings.REDIS_PASSWORD.get_secret_value(),
            database=settings.REDIS_DB,
        )

        pool = await create_pool(redis_settings, default_queue_name="spectra:tasks")

        try:
            # Enqueue the job
            job = await pool.enqueue_job(
                "execute_tool_job",
                tool_id,
                target,
                args,
                timeout,
                output_dir,
            )

            if not job:
                return self._create_error_result(
                    tool_id, target, "Failed to enqueue job"
                )

            # Wait for result with timeout
            job_timeout = (timeout or 300) + 60  # Add buffer for job overhead
            result_data = await job.result(timeout=job_timeout)

            if result_data is None:
                return self._create_error_result(
                    tool_id, target, "Job returned no result"
                )

            # Convert dict back to ToolExecutionResult
            return ToolExecutionResult(**result_data)

        except asyncio.TimeoutError:
            return self._create_error_result(
                tool_id, target, f"Job timed out after {job_timeout}s"
            )
        except Exception as e:
            logger.error("Worker execution failed: %s", e)
            return self._create_error_result(tool_id, target, f"Worker error: {e}")
        finally:
            if hasattr(pool, "aclose"):
                await pool.aclose()
            else:
                await pool.close()

    async def _ensure_tool_installed(self, tool_id: str) -> bool:
        """Ensure a tool is installed via the worker."""
        from arq import create_pool
        from arq.connections import RedisSettings
        from app.core.config import settings

        redis_settings = RedisSettings(
            host=settings.REDIS_HOST,
            port=settings.REDIS_PORT,
            password=settings.REDIS_PASSWORD.get_secret_value(),
            database=settings.REDIS_DB,
        )

        pool = await create_pool(redis_settings, default_queue_name="spectra:tasks")

        try:
            job = await pool.enqueue_job("install_tool_job", tool_id)
            if not job:
                return False

            # Wait for installation (can take a while for large tools)
            result = await job.result(timeout=600)  # 10 min timeout

            if result and result.get("success"):
                # Update local registry status
                registry = get_registry()
                tool = registry.get_tool(tool_id)
                if tool:
                    from app.services.tools.models import ToolStatus

                    tool.status = ToolStatus.READY
                return True
            return False

        except Exception as e:
            logger.error("Tool installation failed: %s", e)
            return False
        finally:
            if hasattr(pool, "aclose"):
                await pool.aclose()
            else:
                await pool.close()

    def _create_error_result(self, tool_id: str, target: str, error: str) -> ToolExecutionResult:
        return ToolExecutionResult(
            tool_id=tool_id,
            target=target,
            success=False,
            stdout="",
            stderr=str(error),
            exit_code=-1, # Internal error
            duration_seconds=0.0
        )


    async def _perform_safety_check(
        self, 
        mission: "Mission", 
        command: str, 
        tool_name: str,
        target: str,
        args: dict[str, Any] | None
    ) -> tuple[bool, str]:
        """Run the command through the Safety Supervisor."""
        safety_input = SafetyInput(
            command=command,
            tool_id=tool_name,
            target=target,
            args=args or {},
        )

        try:
            safety_context = AgentContext(
                mission_id=mission.id,
                session_id=mission.id,
                target=mission.target,
                mission=mission.directive,
                phase="safety_check",
                stealth_mode=False,  # We want the supervisor to be thorough, not stealthy itself
                max_concurrency=1,
            )

            safety_result = await self.safety_supervisor.execute(safety_context, safety_input)
            
            if safety_result.success and isinstance(safety_result.action, SafetyAction):
                if not safety_result.action.allowed:
                    mission.log(f"[BLOCK] Safety check blocked: {safety_result.action.reason}")
                    return False, safety_result.action.reason
            return True, "Safe"
        except Exception as e:
            mission.log(f"Safety check failed verification: {e}")
            return False, str(e)

    async def _perform_safety_check_with_retry(
        self,
        mission: "Mission",
        command: str,
        tool_name: str,
        target: str,
        args: dict[str, Any] | None,
        builder: "CommandBuilder",
        output_dir: Path,
        max_retries: int = 2,
    ) -> tuple[bool, str, dict[str, Any] | None]:
        """
        Run safety check with automatic command fixing on failure.

        Returns:
            Tuple of (is_safe, reason, fixed_args or None)
        """
        current_args = args
        current_command = command

        for attempt in range(max_retries + 1):
            is_safe, reason = await self._perform_safety_check(
                mission, current_command, tool_name, target, current_args
            )

            if is_safe:
                # Return fixed args if we modified them
                return True, "Safe", current_args if attempt > 0 else None

            if attempt < max_retries:
                mission.log(
                    f"[ADAPT] Attempting to fix command (attempt {attempt + 1}/{max_retries})..."
                )

                # Try to fix the command using LLM
                fixed_args = await self._try_fix_command(
                    mission, tool_name, target, current_args, reason
                )

                if fixed_args is not None and fixed_args != current_args:
                    current_args = fixed_args
                    # Rebuild command with fixed args
                    from app.services.tools.models import ToolExecutionRequest

                    fixed_request = ToolExecutionRequest(
                        tool_id=tool_name,
                        target=target,
                        args=fixed_args,
                        timeout=None,
                    )
                    current_command = builder.build_command(
                        fixed_request, output_dir=str(output_dir)
                    )
                    mission.log(f"[INFO] Retrying with fixed args: {fixed_args}")
                else:
                    # Couldn't fix, break out
                    break

        return False, reason, None

    async def _try_fix_command(
        self,
        mission: "Mission",
        tool_name: str,
        target: str,
        args: dict[str, Any] | None,
        error_reason: str,
    ) -> dict[str, Any] | None:
        """Use LLM to try to fix a blocked command."""
        try:
            # Get tool config for context
            registry = get_registry()
            tool = registry.get_tool(tool_name)
            if not tool:
                return None

            prompt = f"""The following command was blocked by safety checks:
Tool: {tool_name}
Target: {target}
Arguments: {args}
Error: {error_reason}

Tool description: {tool.config.description}
Available arguments: {tool.config.execution.args_template}

Please provide ONLY a valid JSON object with corrected arguments that would fix the safety issue.
The arguments must be valid for this tool. Do not include any explanation, just the JSON.

Example response format:
{{"module": "exploit/unix/ftp/vsftpd_234_backdoor", "RHOSTS": "192.168.1.1"}}"""

            llm_response = await self.llm.generate(
                prompt=prompt,
                system_prompt="You are a security tool expert. Fix malformed commands by providing valid arguments as JSON.",
                temperature=0.1,
            )

            # Parse the JSON response - handle LLMResponse object
            import json

            # Extract text from LLMResponse object if needed
            if hasattr(llm_response, "content"):
                response_text = llm_response.content
            elif hasattr(llm_response, "text"):
                response_text = llm_response.text
            else:
                response_text = str(llm_response)

            response_text = response_text.strip()
            if response_text.startswith("```"):
                # Remove code blocks
                lines = response_text.split("\n")
                response_text = "\n".join(l for l in lines if not l.startswith("```"))

            fixed_args = json.loads(response_text)
            if isinstance(fixed_args, dict):
                mission.log(f"[INFO] LLM suggested fix: {fixed_args}")
                return fixed_args

        except Exception as e:
            logger.warning("Failed to fix command via LLM: %s", e)

        return None

    async def _perform_consensus_check(
        self, 
        mission: "Mission", 
        tool_name: str,
        risk_level: str
    ) -> bool:
        """Get consensus for high-risk actions."""
        mission.log(f"[VOTE] High-risk action: {tool_name} ({risk_level})")
        
        # Construct proxy action for consensus check
        # This is a bit of a hack, but VotingSystem expects an Action object
        from app.services.ai.agents.base import AgentAction, ActionRisk
        proxy_action = AgentAction(
            action_type="tool_execution",
            risk_level=ActionRisk.HIGH if risk_level == "high" else ActionRisk.CRITICAL,
            confidence=1.0,
            reasoning=f"Execute high-risk tool {tool_name}"
        )
        
        vote_result = await self.consensus.vote_on_action(
            proxy_action,
            {"target": mission.target, "tool": tool_name},
        )

        if vote_result.status != "approved":
            mission.log(f"[REJECTED] Action blocked by consensus: {vote_result.escalation_reason}")
            return False
            
        mission.log("[APPROVED] Action validated by consensus")
        return True

    def _prepare_output_directory(self, mission_id: str, run_id: str) -> Path:
        """Create and return the output directory path."""
        path = Path("reports/missions") / mission_id / "scans" / run_id
        path.mkdir(parents=True, exist_ok=True)
        return path

    def _validate_tool_name(self, tool_name: str) -> bool:
        """Validate tool name for filesystem safety."""
        return bool(re.match(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$", tool_name))

    def _normalize_tool_name(self, tool_name: str) -> str:
        """
        Normalize tool names to match plugin IDs.

        LLMs often use title-case like "Metasploit Framework" but plugin IDs are lowercase.
        """
        tool_aliases = {
            "metasploit framework": "metasploit",
            "metasploit": "metasploit",
            "hydra": "hydra",
            "nuclei": "nuclei",
            "nmap": "nmap",
            "nikto": "nikto",
            "gobuster": "gobuster",
            "wpscan": "wpscan",
            "sqlmap": "sqlmap",
            "searchsploit": "searchsploit",
            "ffuf": "ffuf",
            "naabu": "naabu",
            "amass": "amass",
        }

        normalized = tool_name.lower().strip()
        return tool_aliases.get(normalized, normalized)

    def _log_success(self, mission: "Mission", tool_name: str, result: ToolExecutionResult) -> None:
        """Log detailed successful execution summary."""
        finding_count = len(result.parsed_findings)
        summary_parts = []
        details = []

        if finding_count > 0:
            findings = result.parsed_findings

            # Collect open ports (nmap, naabu style)
            open_ports = [
                f.get("port")
                for f in findings
                if f.get("state") == "open" and f.get("port")
            ]
            if open_ports:
                summary_parts.append(f"{len(open_ports)} open port(s)")
                details.append(f"Ports: {', '.join(str(p) for p in open_ports[:10])}")
                if len(open_ports) > 10:
                    details[-1] += f"... (+{len(open_ports) - 10} more)"

            # Collect services discovered
            services = [
                f"{f.get('service', 'unknown')}:{f.get('port')}"
                for f in findings
                if f.get("service") and f.get("port")
            ]
            if services and len(services) <= 8:
                details.append(f"Services: {', '.join(services)}")
            elif services:
                details.append(f"Services: {len(services)} discovered")

            # Collect vulnerabilities (nuclei, nikto style)
            vulns = [
                f
                for f in findings
                if f.get("severity")
                or (f.get("info", {}) if isinstance(f.get("info"), dict) else {}).get(
                    "severity"
                )
            ]
            if vulns:
                # Count by severity
                sev_counts = {}
                for v in vulns:
                    sev = (
                        v.get("severity")
                        or (
                            v.get("info", {}) if isinstance(v.get("info"), dict) else {}
                        ).get("severity")
                        or "info"
                    )
                    sev_counts[sev.lower()] = sev_counts.get(sev.lower(), 0) + 1

                sev_strs = []
                for sev in ["critical", "high", "medium", "low", "info"]:
                    if sev in sev_counts:
                        sev_strs.append(f"{sev_counts[sev]} {sev}")

                summary_parts.append(f"{len(vulns)} vulnerability finding(s)")
                if sev_strs:
                    details.append(f"Severity: {', '.join(sev_strs)}")

                # Show top 3 vulnerability names
                vuln_names = [
                    v.get("name")
                    or (
                        v.get("info", {}) if isinstance(v.get("info"), dict) else {}
                    ).get("name")
                    or v.get("template-id", "")
                    for v in vulns[:3]
                ]
                vuln_names = [n for n in vuln_names if n]
                if vuln_names:
                    details.append(f"Found: {', '.join(vuln_names)}")

            # Collect directories/files (gobuster, ffuf style)
            dirs = [
                f.get("url") or f.get("path")
                for f in findings
                if f.get("status") in (200, 301, 302, 403) or f.get("words")
            ]
            if dirs and not open_ports and not vulns:
                summary_parts.append(f"{len(dirs)} path(s) discovered")
                if len(dirs) <= 5:
                    details.append(f"Paths: {', '.join(str(d) for d in dirs)}")

            # Collect credentials (hydra style)
            creds = [f for f in findings if f.get("login") or f.get("password")]
            if creds:
                summary_parts.append(f"{len(creds)} credential(s) found")
                details.append("Valid credentials discovered!")

            # If no specific category matched
            if not summary_parts:
                summary_parts.append(f"{finding_count} finding(s)")
        else:
            summary_parts.append("scan complete, no findings")

        # Build final message
        summary_str = ", ".join(summary_parts)
        duration_str = (
            f" ({result.duration_seconds:.1f}s)" if result.duration_seconds else ""
        )

        mission.log(f"[OK] {tool_name}{duration_str}: {summary_str}")
        for detail in details[:4]:  # Max 4 detail lines
            mission.log(f"    -> {detail}")

    def _update_attack_surface_from_finding(
        self, mission: "Mission", finding: dict[str, Any]
    ) -> None:
        """Update attack surface from a parsed finding."""
        import uuid

        # Handle nmap-style port/service findings
        if finding.get("port") or finding.get("portid"):
            port = finding.get("port") or finding.get("portid")
            try:
                port = int(port)
                mission.add_service(
                    host=finding.get("ip") or finding.get("host") or mission.target,
                    port=port,
                    service=finding.get("service") or finding.get("name"),
                    product=finding.get("product"),
                    version=finding.get("version"),
                )
            except (ValueError, TypeError):
                pass

        # Handle vulnerability findings (from nuclei, etc.)
        severity = finding.get("severity") or finding.get("info", {}).get("severity")
        name = (
            finding.get("name")
            or finding.get("info", {}).get("name")
            or finding.get("template-id")
        )

        if (
            severity
            and name
            and severity.lower() in ("info", "low", "medium", "high", "critical")
        ):
            # Extract CVE ID - may be a list or string
            cve_id = finding.get("cve_id") or finding.get("info", {}).get(
                "classification", {}
            ).get("cve-id")
            if isinstance(cve_id, list):
                cve_id = cve_id[0] if cve_id else None

            mission.add_vulnerability(
                vuln_id=finding.get("template-id") or f"vuln-{uuid.uuid4().hex[:8]}",
                title=name,
                severity=severity,
                cve_id=cve_id,
            )

        # Handle web app findings
        url = finding.get("url") or finding.get("matched-at")
        if url and (finding.get("technologies") or finding.get("matcher-name")):
            techs = finding.get("technologies") or []
            if finding.get("matcher-name"):
                techs.append(finding.get("matcher-name"))
            mission.add_webapp(url=url, technologies=techs)
