"""
Tool Execution Service.

Thin orchestrator that delegates to focused modules:
- validation.py  — tool name checks and registry resolution
- safety_checks.py — SafetySupervisor gate + retry-with-fix
- consensus.py — VotingSystem gate for high-risk actions
- dispatch.py — request building, worker dispatch, result processing
"""

from __future__ import annotations

import asyncio
import html
import logging
from typing import TYPE_CHECKING, Any

from spectra_ai_core.agents.base import AgentContext, ToolAction
from spectra_ai_core.agents.safety import SafetySupervisorAgent
from spectra_ai_core.consensus import VotingSystem

# Keep these imports in *this* module's namespace so that existing tests
# (which ``patch("spectra_tools.service.<Name>")`` ) keep working.
from spectra_common.constants import (
    TOOL_DEFAULT_TIMEOUT,
    TOOL_JOB_BUFFER_TIMEOUT,
    TOOL_MAX_CONCURRENCY,
    TOOL_MAX_RETRIES,
    TOOL_MAX_STDERR_CHARS,
    TOOL_MAX_STDOUT_CHARS,
)
from spectra_domain.jobs import WorkerJobName
from spectra_tools.consensus import perform_consensus_check
from spectra_tools.dispatch import build_execution_request, dispatch_and_process_result
from spectra_tools.interfaces import ToolExecutionMission
from spectra_tools.output import (
    create_error_result,
    normalize_tool_name,
    record_to_memory,
)
from spectra_tools.safety_checks import (
    perform_safety_check,
    perform_safety_check_with_retry,
)
from spectra_tools.validation import validate_and_resolve_tool
from spectra_tools_core.models import ToolExecutionResult

if TYPE_CHECKING:
    from spectra_ai_core.llm import LLMClient
    from spectra_mission.mission import Mission

logger = logging.getLogger(__name__)


def sanitize_tool_output(output: str) -> str:
    """Sanitize tool output for safe display in the UI."""
    return html.escape(output)


class StandaloneMissionAdapter:
    """Adapts a standalone execution to the Mission interface."""

    def __init__(self, target: str, job_id: str | None = None, user_id: str | None = None):
        import uuid as _uuid

        self.id = job_id or str(_uuid.uuid4())
        self.target = target
        self.user_id = user_id or "__standalone__"
        self.directive = f"Execute tool against {target}"
        self.findings: list[dict[str, Any]] = []
        self.tool_runs: list[str] = []

    def log(self, message: str) -> None:
        logger.info("[%s] %s", self.id, message)

    def add_finding(self, finding: dict[str, Any]) -> None:
        self.findings.append(finding)

    def record_tool_run(self, tool_name: str) -> None:
        self.tool_runs.append(tool_name)


class ToolExecutionService:
    """
    Service responsible for executing security tools safely.

    Orchestrates validation, safety, consensus, and execution dispatch
    by delegating to focused helper modules.
    """

    # --- Tuneable constants (defined in spectra_common.constants) ------------------
    DEFAULT_TIMEOUT = TOOL_DEFAULT_TIMEOUT
    JOB_BUFFER_TIMEOUT = TOOL_JOB_BUFFER_TIMEOUT
    MAX_STDOUT_CHARS = TOOL_MAX_STDOUT_CHARS
    MAX_STDERR_CHARS = TOOL_MAX_STDERR_CHARS
    MAX_CONCURRENCY = TOOL_MAX_CONCURRENCY
    MAX_RETRIES = TOOL_MAX_RETRIES

    @staticmethod
    def _get_queue_name(mission_id: str) -> str:
        """Get the queue name for tool execution.

        Uses mission-specific queue if sandbox container exists,
        otherwise routes to shared tools worker queue.
        """
        from spectra_tools.sandbox import get_sandbox_pool
        from spectra_tools.sandbox.models import SandboxInfo

        pool = get_sandbox_pool()
        if pool and pool.available:
            return SandboxInfo.make_queue_name(mission_id)

        # Shared tools worker in containerized deployment
        from spectra_common.config import settings

        return settings.TOOL_QUEUE_NAME

    def __init__(self, llm_client: LLMClient):
        """Initialize with LLM client for safety/consensus agents."""
        self.llm = llm_client
        self.safety_supervisor = SafetySupervisorAgent(llm_client)
        self.consensus = VotingSystem(llm_client)

        # Concurrency limit
        self._semaphore = asyncio.Semaphore(self.MAX_CONCURRENCY)

    # --- Public entry points --------------------------------------------------

    async def execute_tool_action(self, mission: Mission, action: ToolAction, context: AgentContext) -> bool:
        """Execute a tool action generated by an agent."""
        result = await self.execute_request(
            mission=mission,
            tool_name=action.tool_name,
            target=action.target,
            args=action.tool_args,
            timeout=action.estimated_duration,
            risk_level=action.risk_level,
        )
        return result.success

    async def execute_custom_script(
        self,
        mission: ToolExecutionMission,
        script_content: str,
        language: str,
        target: str,
        args: list[str] | None = None,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> ToolExecutionResult:
        """Execute a custom generated script via the worker."""
        mission.log(f"[EXEC] Running custom {language} script against {target}")

        is_safe, reason = await self._perform_safety_check(
            mission, script_content, f"custom_{language}_script", target, {}
        )
        if not is_safe:
            mission.log(f"[BLOCK] Custom script blocked by safety check: {reason}")
            return create_error_result(
                f"custom_{language}_script",
                target,
                f"Blocked by Safety Supervisor: {reason}",
            )

        from spectra_infra.queue import Job, PostgresJobQueue

        try:
            queue_name = self._get_queue_name(mission.id) if hasattr(mission, "id") and mission.id else "default"
            queue = PostgresJobQueue(queue_name)
            job_id = await queue.enqueue_job(
                WorkerJobName.EXECUTE_SCRIPT,
                content=script_content,
                language=language,
                target=target,
                args=args,
                timeout=timeout,
            )

            job = Job(job_id)
            result_data = await job.result(timeout=timeout + self.JOB_BUFFER_TIMEOUT)

            if not result_data:
                return create_error_result("custom_script", target, "Job returned no result")

            success = result_data.get("success", False)
            mission.log(f"[{'OK' if success else 'FAIL'}] Script execution finished")
            if not success:
                mission.log(f"Error: {result_data.get('stderr')}")

            return ToolExecutionResult(
                tool_id=f"custom_{language}_script",
                target=target,
                success=success,
                exit_code=result_data.get("exit_code", -1),
                stdout=result_data.get("stdout", ""),
                stderr=result_data.get("stderr", ""),
                duration_seconds=0.0,
            )

        except (OSError, TimeoutError, ValueError, RuntimeError) as e:
            logger.error("Failed to execute custom script: %s", e)
            return create_error_result("custom_script", target, str(e))

    async def execute_request(
        self,
        mission: Mission,
        tool_name: str,
        target: str,
        args: dict[str, Any] | None = None,
        timeout: int | None = None,
        risk_level: str = "low",
    ) -> ToolExecutionResult:
        """Execute a tool request with full safety and consensus checks."""
        try:
            tool_name = normalize_tool_name(tool_name)

            tool, error = await self._validate_and_resolve_tool(
                mission,
                tool_name,
                target,
                args,
            )
            if error is not None:
                return error
            if tool is None:
                return create_error_result(tool_name, target, f"Tool not found: {tool_name}")

            request, adapter, full_command, output_dir = build_execution_request(
                mission,
                tool,
                tool_name,
                target,
                args,
                timeout,
            )

            full_command, blocked = await self._apply_safety_and_consensus(
                mission,
                tool_name,
                target,
                args,
                risk_level,
                adapter,
                output_dir,
                request,
                full_command,
            )
            if blocked is not None:
                return blocked

            result = await self._dispatch_and_process_result(
                mission,
                tool,
                tool_name,
                target,
                args,
                request,
                adapter,
                full_command,
                output_dir,
            )

            self._apply_red_flag_gate(mission, tool, result)
            await self._apply_output_parsing_gate(mission, tool, result)

            record_to_memory(mission, tool_name, target, args, result)

            # Record to demo recorder if available
            recorder = getattr(mission, "_demo_recorder", None)
            if recorder:
                try:
                    recorder.record_tool_start(tool_name, target, args or {})
                    if result.stdout:
                        output_preview = result.stdout[:500]
                        recorder.record_tool_output(output_preview)
                    findings_count = len(result.parsed_findings) if result.parsed_findings else 0
                    recorder.record_tool_result(tool_name, result.success, findings_count)
                except (OSError, RuntimeError, AttributeError) as e:
                    logger.debug("Demo recording failed: %s", e)

            return result

        except (OSError, TimeoutError, ValueError, KeyError, RuntimeError) as e:
            msg = f"Critical error executing {tool_name}: {e}"
            mission.log(msg)
            logger.error(msg, exc_info=True)
            return create_error_result(tool_name, target, str(e))

    # --- Delegated helpers ----------------------------------------------------

    def _apply_red_flag_gate(self, mission: Mission, tool, result: ToolExecutionResult) -> None:
        """MAKER RED_FLAG gate: mark structurally corrupt/incomplete tool output.

        Only successful runs are checked (failures already carry an error). Flagged
        output is annotated (not discarded) so the parser/agent loop can treat it as
        low-trust rather than silently patching it.
        """
        if not result.success or not result.stdout:
            return
        try:
            expected_format = "structured"
            parsing = getattr(tool, "parsing", None)
            fmt = getattr(getattr(parsing, "format", None), "value", None)
            if fmt in ("json", "xml"):
                expected_format = fmt
            verdict = self.consensus.red_flag_check(result.stdout, expected_format)
            if verdict.get("flagged") and verdict.get("severity") == "error":
                result.integrity_warning = verdict.get("reason") or "Output flagged by integrity gate"
                mission.log(f"[RED-FLAG] {result.tool_id} output flagged: {result.integrity_warning}")
        except (AttributeError, ValueError, RuntimeError) as e:
            logger.debug("Red-flag gate skipped for %s: %s", result.tool_id, e)

    async def _apply_output_parsing_gate(self, mission: Mission, tool, result: ToolExecutionResult) -> None:
        """MAKER OUTPUT_PARSING gate: recover structured facts via consensus extraction.

        Only fires when the tool opted into LLM extraction, the deterministic parser
        recovered nothing, the run succeeded, and the output was not red-flagged. This
        bounds LLM cost to the cases where structured facts would otherwise be lost.
        """
        if not result.success or result.integrity_warning or result.parsed_findings:
            return
        parsing = getattr(tool, "parsing", None)
        if not getattr(parsing, "llm_extraction", False):
            return
        if not result.stdout or len(result.stdout.strip()) < 40:
            return
        try:
            from spectra_common.config import settings

            voters = max(getattr(settings, "CONSENSUS_OUTPUT_PARSING_VOTERS", 2), 1)
            verdict = await self.consensus.vote_on_output_parsing(
                result.stdout,
                extraction_hint=getattr(parsing, "extraction_hint", "") or "",
                num_voters=voters,
            )
            facts = verdict.get("facts") or []
            if facts:
                result.parsed_findings = facts
                mission.log(
                    f"[OUTPUT-PARSING] recovered {len(facts)} fact(s) for {result.tool_id} "
                    f"via {verdict.get('voters', 0)}-voter consensus"
                )
        except (AttributeError, ValueError, RuntimeError) as e:
            logger.debug("Output-parsing gate skipped for %s: %s", result.tool_id, e)

    def _apply_framework_enforcement(
        self, mission: Mission, adapter, tool_name: str, target: str, full_command: str
    ) -> ToolExecutionResult | None:
        """Validate a tool run against the active framework before execution.

        Forbidden techniques and unconfirmed authorization are always blocked. Out-of-phase
        techniques are blocked only in ``strict`` mode; otherwise they are logged as advisory.
        Unmappable tools (no matching technique category) are blocked. Unknown
        metadata must not create an authorization or target-scope bypass.
        Returns an error result when blocked, else ``None``. Enforcement
        failures fail closed.
        """
        try:
            from spectra_common.config import settings
            from spectra_mission.coordination.scope_enforcer import ScopeEnforcer
            from spectra_mission.framework_loader import get_framework

            framework_id = getattr(mission, "pentest_framework", None)
            phase = getattr(mission, "current_phase", "") or ""
            config = getattr(adapter, "config", None)
            if config is None:
                return create_error_result(
                    tool_name, target, "Blocked: tool configuration unavailable for framework check"
                )
            if not phase:
                return create_error_result(tool_name, target, "Blocked: mission execution phase is unavailable")

            # Build the tool's signal set from category, capabilities and tags.
            signals: set[str] = set()
            category = getattr(config, "category", None)
            if category:
                signals.add(str(category).lower())
            metadata = getattr(config, "metadata", None)
            for cap in getattr(metadata, "capabilities", []) or []:
                signals.add(str(cap).lower())
            for tag in getattr(metadata, "tags", []) or []:
                signals.add(str(tag).lower())

            spec = get_framework(framework_id)
            matches = [tc for tc in spec.technique_categories if signals & {t.lower() for t in tc.tool_types}]
            if not matches:
                reason = f"Tool '{tool_name}' is not mapped to a framework technique"
                mission.log(f"[FRAMEWORK-BLOCK] {tool_name}: {reason}")
                return create_error_result(tool_name, target, f"Blocked by framework policy: {reason}")

            # Prefer a technique allowed in the current phase; fall back to the first match.
            technique = next((tc for tc in matches if phase in tc.allowed_in_phases), matches[0])

            verdict = ScopeEnforcer(mission, framework_id).validate(full_command, technique.id, phase)
            if verdict.allowed:
                return None

            hard = [c for c in verdict.blocked_checks if c.check_type in ("forbidden_technique", "authorization")]
            if hard:
                reason = hard[0].reason
                mission.log(f"[FRAMEWORK-BLOCK] {tool_name}: {reason}")
                return create_error_result(tool_name, target, f"Blocked by framework policy: {reason}")

            phase_violation = next((c for c in verdict.blocked_checks if c.check_type == "framework_phase"), None)
            if phase_violation:
                mode = getattr(settings, "FRAMEWORK_ENFORCEMENT_MODE", "advisory")
                if mode == "strict":
                    mission.log(f"[FRAMEWORK-BLOCK] {tool_name}: {phase_violation.reason}")
                    return create_error_result(
                        tool_name, target, f"Blocked by framework phase gating: {phase_violation.reason}"
                    )
                mission.log(
                    f"[FRAMEWORK-ADVISORY] {tool_name} ({technique.id}) out of phase '{phase}': {phase_violation.reason}"
                )
            return None
        except (AttributeError, ValueError, RuntimeError, KeyError) as e:
            logger.error("Framework enforcement failed closed for %s: %s", tool_name, e)
            return create_error_result(tool_name, target, "Blocked: framework enforcement unavailable")

    async def _validate_and_resolve_tool(self, mission, tool_name, target, args):
        return await validate_and_resolve_tool(
            mission,
            tool_name,
            target,
            args,
        )

    async def _apply_safety_and_consensus(
        self,
        mission,
        tool_name,
        target,
        args,
        risk_level,
        adapter,
        output_dir,
        request,
        full_command,
    ) -> tuple[str, ToolExecutionResult | None]:
        """Run framework enforcement, safety check with retry, and consensus check."""
        blocked = self._apply_framework_enforcement(mission, adapter, tool_name, target, full_command)
        if blocked is not None:
            return full_command, blocked

        is_safe, reason, fixed_args = await self._perform_safety_check_with_retry(
            mission, full_command, tool_name, target, args, adapter, output_dir
        )
        if not is_safe:
            mission.record_tool_run(
                tool_name,
                args=args,
                command=full_command,
                success=False,
                error=f"Safety blocked: {reason}",
            )
            return full_command, create_error_result(tool_name, target, f"Blocked by Safety Supervisor: {reason}")

        if fixed_args is not None:
            request.args = fixed_args
            full_command = adapter.build_command(request, output_dir=output_dir)
            mission.log(f"[CMD] Fixed command: {full_command[:200]}{'...' if len(full_command) > 200 else ''}")

        if risk_level in ("high", "critical"):
            is_approved = await self._perform_consensus_check(mission, tool_name, risk_level)
            if not is_approved:
                return full_command, create_error_result(tool_name, target, "Blocked by Consensus")

        return full_command, None

    async def _dispatch_and_process_result(
        self,
        mission,
        tool,
        tool_name,
        target,
        args,
        request,
        adapter,
        full_command,
        output_dir,
    ) -> ToolExecutionResult:
        queue_name = self._get_queue_name(mission.id) if mission.id else "default"
        return await dispatch_and_process_result(
            mission,
            tool,
            tool_name,
            target,
            args,
            request,
            adapter,
            full_command,
            output_dir,
            semaphore=self._semaphore,
            queue_name=queue_name,
            default_timeout=self.DEFAULT_TIMEOUT,
            buffer_timeout=self.JOB_BUFFER_TIMEOUT,
            max_stdout_chars=self.MAX_STDOUT_CHARS,
            max_stderr_chars=self.MAX_STDERR_CHARS,
        )

    # --- Safety / Consensus (delegated) ----------------------------------------

    async def _perform_safety_check(
        self,
        mission,
        command,
        tool_name,
        target,
        args,
    ) -> tuple[bool, str]:
        return await perform_safety_check(
            mission,
            command,
            tool_name,
            target,
            args,
            self.safety_supervisor,
        )

    async def _perform_safety_check_with_retry(
        self,
        mission,
        command,
        tool_name,
        target,
        args,
        builder,
        output_dir,
        max_retries=MAX_RETRIES,
    ) -> tuple[bool, str, dict[str, Any] | None]:
        return await perform_safety_check_with_retry(
            mission,
            command,
            tool_name,
            target,
            args,
            builder,
            output_dir,
            self.safety_supervisor,
            self.llm,
            max_retries,
        )

    async def _perform_consensus_check(
        self,
        mission,
        tool_name,
        risk_level,
    ) -> bool:
        return await perform_consensus_check(
            mission,
            tool_name,
            risk_level,
            self.consensus,
        )
